/**
 * Note: This file was auto-generated by TI PinMux on 10/24/2019 at 12:03:39 PM.
 *
 * \file  boardPadDelayTune.h
 *
 * \brief   This file contain manual/vritual iodelay mode definitions
 *
 * \copyright Copyright (CU) 2015-2018 Texas Instruments Incorporated - 
 *             http://www.ti.com/
 */

/**
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *    Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the
 *    distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */
 



#define GMAC_RGMII0_MANUAL1 /* GMAC RGMII0 with Transmit Clock Internal Delay Enabled Timings */
#define MMC1_DS_PLB_SDR12_PLB_DEFAULT /* MMC1 DS (Pad Loopback) and SDR12 (Pad Loopback) Default Timings */
/*#define MMC1_DDR50_PLB */ /* MMC1 DDR50 (Pad Loopback) Timings */
/*#define MMC1_SDR_104 */ /* MMC1 SDR104 Timings */
/*#define MMC1_HS_SDR12_ILB_SDR25 */ /* MMC1 HS (Internal Loopback and Pad Loopback), SDR12 (Internal Loopback), SDR25 Timings (Internal Loopback and Pad Loopback) */
/*#define MMC1_SDR50_PLB */ /* MMC1 SDR50 (Pad Loopback) Timings */
/*#define MMC1_DS_ILB */ /* MMC1 DS (Internal Loopback) Timings */
/*#define MMC1_SDR50_ILB */ /* MMC1 SDR50 (Internal Loopback) Timings */
/*#define MMC1_DDR50_ILB */ /* MMC1 DDR50 (Internal Loopback) Timings */
/*#define MMC2_STD_PLB_HS_PLB_DDR_PLB */ /* MMC2 Standard (Pad Loopback), High Speed (Pad Loopback), and DDR (Pad Loopback) Timings */
/*#define MMC2_DDR_ILB */ /* MMC2 DDR (Internal Loopback) Timings */
/*#define MMC2_STD_ILB_HS_ILB */ /* MMC2 Standard (Internal Loopback), High Speed (Internal Loopback) Timings */
#define MMC2_HS200 /* MMC2 HS200 Timings */
/*#define MMC4_HS_SDR12_SDR25 */ /* MMC4 SDR12, HS, SDR25 Timings */
#define MMC4_DS /* MMC4 DS Timings */
/*#define PR1_PRU1_DEFAULT */ /* PRU-ICSS1 PRU1 Default Timings */
#define PR1_PRU1_DIR_IN /* PRU-ICSS1 PRU1 Direct Input Mode Timings */
/*#define PR1_PRU1_PAR_CAP */ /* PRU-ICSS1 PRU1 Parallel Capture Mode Timings */
/*#define PR2_PRU0_DEFAULT */ /* PRU-ICSS2 PRU0 Default Timings */
#define PR2_PRU0_DIR_IN1 /* PRU-ICSS2 PRU0 IOSET1 Direct Input Mode Timings */
/*#define PR2_PRU0_PAR_CAP1 */ /* PRU-ICSS2 PRU0 IOSET1 Parallel Capture Mode Timings */

/* MODE RE-DEFINITIONS */

#ifdef GMAC_RGMII0_MANUAL1
     #define GMAC_RGMII0_MANUAL1
#endif
#ifdef MMC1_DS_PLB_SDR12_PLB_DEFAULT
     #define MMC1_DEFAULT
#endif
#ifdef MMC1_DDR50_PLB
     #define MMC1_DDR_MANUAL1
#endif
#ifdef MMC1_SDR_104
     #define MMC1_SDR104_MANUAL1
#endif
#ifdef MMC1_HS_SDR12_ILB_SDR25
     #define MMC1_VIRTUAL1
#endif
#ifdef MMC1_SDR50_PLB
     #define MMC1_VIRTUAL2
#endif
#ifdef MMC1_DS_ILB
     #define MMC1_VIRTUAL5
#endif
#ifdef MMC1_SDR50_ILB
     #define MMC1_VIRTUAL6
#endif
#ifdef MMC1_DDR50_ILB
     #define MMC1_VIRTUAL7
#endif
#ifdef MMC2_STD_PLB_HS_PLB_DDR_PLB
     #define MMC2_DEFAULT
#endif
#ifdef MMC2_DDR_ILB
     #define MMC2_DDR_LB_MANUAL1
#endif
#ifdef MMC2_STD_ILB_HS_ILB
     #define MMC2_STD_HS_LB_MANUAL1
#endif
#ifdef MMC2_HS200
     #define MMC2_HS200_MANUAL1
#endif
#ifdef MMC4_HS_SDR12_SDR25
     #define MMC4_MANUAL1
#endif
#ifdef MMC4_DS
     #define MMC4_DS_MANUAL1
#endif
#ifdef PR1_PRU1_DEFAULT
     #define PRUSS1_PRU1_DEFAULT
#endif
#ifdef PR1_PRU1_DIR_IN
     #define PR1_PRU1_DIR_IN_MANUAL
#endif
#ifdef PR1_PRU1_PAR_CAP
     #define PR1_PRU1_PAR_CAP_MANUAL
#endif
#ifdef PR2_PRU0_DEFAULT
     #define PRUSS2_PRU0_DEFAULT
#endif
#ifdef PR2_PRU0_DIR_IN1
     #define PR2_PRU0_DIR_IN_MANUAL1
#endif
#ifdef PR2_PRU0_PAR_CAP1
     #define PR2_PRU0_PAR_CAP_MANUAL1
#endif
