/**
 * Note: This file was auto-generated by TI PinMux on 10/27/2019 at 1:19:08 PM.
 *
 * \file  boardPadDelayInit.c
 *
 * \brief   This file contain manual/vritual iodelay mode definitions
 *
 * \copyright Copyright (CU) 2015-2018 Texas Instruments Incorporated - 
 *             http://www.ti.com/
 */

/**
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *    Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the
 *    distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */

#include <stdint.h>
#include "boardPadDelay.h"
#include "boardPadDelayTune.h"


#if defined(_TMS320C6X) || defined(__TI_ARM_V7M4__)
#ifndef __cplusplus
#pragma DATA_SECTION (pad, "BOARD_IO_DELAY_DATA");
#else
#pragma DATA_SECTION ("BOARD_IO_DELAY_DATA");
#endif
const boardPadDelayCfg_t pad[] = {
#else
const boardPadDelayCfg_t pad[] __attribute__((section("BOARD_IO_DELAY_DATA"))) = {
#endif
/** {PADCONF_REG_OFFSET, PADCONF_VALUE, {CFG_X_IN offset, aDelay, gDelay}, {CFG_X_OEN offset, aDelay, gDelay}, {CFG_X_OUT offset, aDelay, gDelay}} **/

/* DEBUGSS - tms on F18 - MyDEBUGSS1 */
     {0x1830, 0x60000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* DEBUGSS - tdi on D23 - MyDEBUGSS1 */
     {0x1834, 0xE0000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* DEBUGSS - tdo on F19 - MyDEBUGSS1 */
     {0x1838, 0x10000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* DEBUGSS - tclk on E20 - MyDEBUGSS1 */
     {0x183C, 0x40000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* DEBUGSS - trstn on D20 - MyDEBUGSS1 */
     {0x1840, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* DEBUGSS - rtck on E18 - MyDEBUGSS1 */
     {0x1844, 0x10000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* DEBUGSS - emu0 on G21 - MyDEBUGSS1 */
     {0x1848, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* DEBUGSS - emu1 on D24 - MyDEBUGSS1 */
     {0x184C, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* eQEP3 - eQEP3A_in on C2 - QEP3 */
     {0x159C, 0x4000A, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* eQEP3 - eQEP3B_in on C3 - QEP3 */
     {0x15A0, 0x4000A, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* eQEP2 - eQEP2A_in on AG6 - QEP2 */
     {0x150C, 0x4000A, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* eQEP2 - eQEP2B_in on AH4 - QEP2 */
     {0x1510, 0x4000A, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* eQEP1 - eQEP1A_in on AD9 - QEP1 */
     {0x14E4, 0x4000A, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* eQEP1 - eQEP1B_in on AF9 - QEP1 */
     {0x14E8, 0x4000A, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* MDIO - mdio_mclk on V1 - MyGMAC_MDIO1 */
     {0x163C, 0x90000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* MDIO - mdio_d on U4 - MyGMAC_MDIO1 */
     {0x1640, 0x90000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GMAC0 - rgmii0_rxd1 on Y2 - ETH0_MII */
#ifdef GMAC_RGMII0_MANUAL1
     {0x1678, 0x50100, {0x714, 139, 1081}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif

/* GMAC0 - rgmii0_rxd2 on V3 - ETH0_MII */
#ifdef GMAC_RGMII0_MANUAL1
     {0x1674, 0x50100, {0x720, 195, 1100}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif

/* GMAC0 - rgmii0_rxd3 on V4 - ETH0_MII */
#ifdef GMAC_RGMII0_MANUAL1
     {0x1670, 0x50100, {0x72C, 239, 1216}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif

/* GMAC0 - rgmii0_rxd0 on W2 - ETH0_MII */
#ifdef GMAC_RGMII0_MANUAL1
     {0x167C, 0x50100, {0x708, 123, 1047}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif

/* GMAC0 - rgmii0_txd0 on U6 - ETH0_MII */
#ifdef GMAC_RGMII0_MANUAL1
     {0x1664, 0x10100, {0x0, 0, 0}, {0x0, 0, 0}, {0x758, 339, 162}},
#endif

/* GMAC0 - rgmii0_txd1 on V6 - ETH0_MII */
#ifdef GMAC_RGMII0_MANUAL1
     {0x1660, 0x10100, {0x0, 0, 0}, {0x0, 0, 0}, {0x764, 146, 94}},
#endif

/* GMAC0 - rgmii0_txd2 on U7 - ETH0_MII */
#ifdef GMAC_RGMII0_MANUAL1
     {0x165C, 0x10100, {0x0, 0, 0}, {0x0, 0, 0}, {0x770, 0, 27}},
#endif

/* GMAC0 - rgmii0_txd3 on V7 - ETH0_MII */
#ifdef GMAC_RGMII0_MANUAL1
     {0x1658, 0x10100, {0x0, 0, 0}, {0x0, 0, 0}, {0x77C, 291, 205}},
#endif

/* GMAC0 - rgmii0_txc on W9 - ETH0_MII */
#ifdef GMAC_RGMII0_MANUAL1
     {0x1650, 0x10100, {0x0, 0, 0}, {0x0, 0, 0}, {0x740, 89, 0}},
#endif

/* GMAC0 - rgmii0_txctl on V9 - ETH0_MII */
#ifdef GMAC_RGMII0_MANUAL1
     {0x1654, 0x10100, {0x0, 0, 0}, {0x0, 0, 0}, {0x74C, 15, 125}},
#endif

/* GMAC0 - rgmii0_rxc on U5 - ETH0_MII */
#ifdef GMAC_RGMII0_MANUAL1
     {0x1668, 0x50100, {0x6F0, 260, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif

/* GMAC0 - rgmii0_rxctl on V5 - ETH0_MII */
#ifdef GMAC_RGMII0_MANUAL1
     {0x166C, 0x50100, {0x6FC, 0, 1412}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif

/* GPIO2 - gpio2_30 on AG8 - GPIO2 */
     {0x14DC, 0x6000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO3 - gpio3_3 on AF8 - GPIO3 */
     {0x14F0, 0x4000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO3 - gpio3_7 on AH6 - GPIO3 */
     {0x1500, 0x4000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO3 - gpio3_12 on AG4 - GPIO3 */
     {0x1514, 0x4000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO3 - gpio3_13 on AG2 - GPIO3 */
     {0x1518, 0x5000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO3 - gpio3_14 on AG3 - GPIO3 */
     {0x151C, 0x0000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO3 - gpio3_15 on AG5 - GPIO3 */
     {0x1520, 0x0000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO3 - gpio3_17 on AF6 - GPIO3 */
     {0x1528, 0x0000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO3 - gpio3_18 on AF3 - GPIO3 */
     {0x152C, 0x2000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO3 - gpio3_20 on AF1 - GPIO3 */
     {0x1534, 0x4000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO3 - gpio3_21 on AE3 - GPIO3 */
     {0x1538, 0x0000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO3 - gpio3_22 on AE5 - GPIO3 */
     {0x153C, 0x2000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO3 - gpio3_23 on AE1 - GPIO3 */
     {0x1540, 0x5000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO3 - gpio3_24 on AE2 - GPIO3 */
     {0x1544, 0x4000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO3 - gpio3_27 on AD3 - GPIO3 */
     {0x1550, 0x0000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO4 - gpio4_3 on D1 - GPIO4 */
     {0x1570, 0x4000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO4 - gpio4_9 on F5 - GPIO4 */
     {0x1588, 0x4000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO4 - gpio4_10 on E6 - GPIO4 */
     {0x158C, 0x4000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO4 - gpio4_11 on D3 - GPIO4 */
     {0x1590, 0x4000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO4 - gpio4_13 on D5 - GPIO4 */
     {0x1598, 0x4000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO4 - gpio4_17 on A12 - GPIO4 */
     {0x16E0, 0xC000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO4 - gpio4_18 on E14 - GPIO4 */
     {0x16E4, 0xD000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO4 - gpio4_19 on D11 - GPIO4 */
     {0x15C8, 0x4000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO4 - gpio4_20 on B10 - GPIO4 */
     {0x15CC, 0x4000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO4 - gpio4_22 on C11 - GPIO4 */
     {0x15D4, 0x4000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO4 - gpio4_23 on E11 - GPIO4 */
     {0x15D8, 0x4000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO4 - gpio4_25 on D6 - GPIO4 */
     {0x15AC, 0x4000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO4 - gpio4_26 on C5 - GPIO4 */
     {0x15B0, 0x4000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO4 - gpio4_28 on B3 - GPIO4 */
     {0x15B8, 0x4000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO8 - gpio8_0 on F11 - GPIO8 */
     {0x15DC, 0x4000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO8 - gpio8_1 on G10 - GPIO8 */
     {0x15E0, 0x4000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO8 - gpio8_2 on F10 - GPIO8 */
     {0x15E4, 0x4000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO8 - gpio8_3 on G11 - GPIO8 */
     {0x15E8, 0x4000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO8 - gpio8_8 on E8 - GPIO8 */
     {0x15FC, 0x4000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO8 - gpio8_9 on D9 - GPIO8 */
     {0x1600, 0x4000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO8 - gpio8_10 on D7 - GPIO8 */
     {0x1604, 0x5000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO8 - gpio8_11 on D8 - GPIO8 */
     {0x1608, 0x4000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO8 - gpio8_14 on C8 - GPIO8 */
     {0x1614, 0x4000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO8 - gpio8_15 on C7 - GPIO8 */
     {0x1618, 0x4000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO8 - gpio8_17 on B8 - GPIO8 */
     {0x1620, 0x4000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO8 - gpio8_18 on A7 - GPIO8 */
     {0x1624, 0x4000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO5 - gpio5_0 on B14 - GPIO5 */
     {0x16AC, 0x4000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO5 - gpio5_5 on J11 - GPIO5 */
     {0x16C0, 0x0000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO5 - gpio5_7 on F13 - GPIO5 */
     {0x16C8, 0x2000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO5 - gpio5_10 on B12 - GPIO5 */
     {0x16D4, 0xC000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO5 - gpio5_11 on A11 - GPIO5 */
     {0x16D8, 0xC000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO5 - gpio5_12 on B13 - GPIO5 */
     {0x16DC, 0xC000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO5 - gpio5_18 on V2 - GPIO5 */
     {0x1648, 0xC000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO5 - gpio5_19 on Y1 - GPIO5 */
     {0x164C, 0xC000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO6 - gpio6_4 on A13 - GPIO6 */
     {0x16E8, 0xC000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO6 - gpio6_5 on G14 - GPIO6 */
     {0x16EC, 0xC000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO6 - gpio6_6 on F14 - GPIO6 */
     {0x16F0, 0xC000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO6 - gpio6_15 on F20 - GPIO6 */
     {0x168C, 0x40000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO6 - gpio6_16 on F21 - GPIO6 */
     {0x1690, 0x60000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO6 - gpio6_17 on D18 - GPIO6 */
     {0x1694, 0x4000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO6 - gpio6_18 on E17 - GPIO6 */
     {0x1698, 0x4000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO6 - gpio6_19 on B26 - GPIO6 */
     {0x169C, 0x4000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO6 - gpio6_20 on C23 - GPIO6 */
     {0x16A0, 0x4000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO6 - gpio6_29 on AD4 - GPIO6 */
     {0x177C, 0x6000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO6 - gpio6_30 on AC4 - GPIO6 */
     {0x1780, 0x6000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO6 - gpio6_31 on AC7 - GPIO6 */
     {0x1784, 0x6000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO1 - gpio1_22 on AC8 - GPIO1 */
     {0x1794, 0x6000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO1 - gpio1_23 on AD6 - GPIO1 */
     {0x1798, 0x6000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO1 - gpio1_24 on AB8 - GPIO1 */
     {0x179C, 0x6000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO1 - gpio1_25 on AB5 - GPIO1 */
     {0x17A0, 0x6000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO7 - gpio7_0 on AC6 - GPIO7 */
     {0x1788, 0x6000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO7 - gpio7_1 on AC9 - GPIO7 */
     {0x178C, 0x6000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO7 - gpio7_2 on AC3 - GPIO7 */
     {0x1790, 0x6000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO7 - gpio7_11 on A22 - GPIO7 */
     {0x17B4, 0x4000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO7 - gpio7_16 on G17 - GPIO7 */
     {0x17C8, 0xD000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* GPIO7 - gpio7_17 on B24 - GPIO7 */
     {0x17CC, 0xD000E, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* HDMI - hdmi1_data2x on AG19 - MyHDMI1 */
     /* {NOT FOUND, 0x10000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* HDMI - hdmi1_data2y on AH19 - MyHDMI1 */
     /* {NOT FOUND, 0x10000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* HDMI - hdmi1_data1x on AG18 - MyHDMI1 */
     /* {NOT FOUND, 0x10000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* HDMI - hdmi1_data1y on AH18 - MyHDMI1 */
     /* {NOT FOUND, 0x10000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* HDMI - hdmi1_data0x on AG17 - MyHDMI1 */
     /* {NOT FOUND, 0x10000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* HDMI - hdmi1_data0y on AH17 - MyHDMI1 */
     /* {NOT FOUND, 0x10000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* HDMI - hdmi1_clockx on AG16 - MyHDMI1 */
     /* {NOT FOUND, 0x10000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* HDMI - hdmi1_clocky on AH16 - MyHDMI1 */
     /* {NOT FOUND, 0x10000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* HDMI - hdmi1_cec on G19 - MyHDMI1 */
     {0x17D4, 0xD0006, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* HDMI - hdmi1_hpd on B21 - MyHDMI1 */
     {0x17B8, 0xD0006, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* HDMI - hdmi1_ddc_scl on C25 - MyHDMI1 */
     {0x1808, 0x60001, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* HDMI - hdmi1_ddc_sda on F17 - MyHDMI1 */
     {0x180C, 0x60001, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* I2C4 - i2c4_scl on R6 - I2C4 */
     {0x1440, 0x60007, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* I2C4 - i2c4_sda on T9 - I2C4 */
     {0x1444, 0x60007, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* I2C5 - i2c5_scl on F12 - I2C5 */
     {0x16B8, 0xE000A, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* I2C5 - i2c5_sda on G12 - I2C5 */
     {0x16B4, 0xE000A, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* I2C1 - i2c1_scl on C20 - I2C1_LOCAL */
     {0x1804, 0x60000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* I2C1 - i2c1_sda on C21 - I2C1_LOCAL */
     {0x1800, 0x60000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* INTC - nmin_dsp on D21 - MyINTC1 */
     {0x1860, 0x60000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* MMC1 - mmc1_clk on W6 - MMC1_MICRO */
#ifdef MMC1_DEFAULT
     {0x1754, 0x60000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef MMC1_DDR_MANUAL1
     {0x1754, 0x60100, {0x618, 1076, 330}, {0x0, 0, 0}, {0x620, 1271, 0}},
#endif
#ifdef MMC1_SDR104_MANUAL1
     {0x1754, 0x60100, {0x0, 0, 0}, {0x0, 0, 0}, {0x620, 600, 400}},
#endif
#ifdef MMC1_VIRTUAL1
     {0x1754, 0x601B0, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef MMC1_VIRTUAL2
     {0x1754, 0x601A0, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef MMC1_VIRTUAL5
     {0x1754, 0x60170, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef MMC1_VIRTUAL6
     {0x1754, 0x60160, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef MMC1_VIRTUAL7
     {0x1754, 0x60150, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif

/* MMC1 - mmc1_cmd on Y6 - MMC1_MICRO */
#ifdef MMC1_DEFAULT
     {0x1758, 0x60000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef MMC1_DDR_MANUAL1
     {0x1758, 0x60100, {0x624, 722, 0}, {0x628, 0, 0}, {0x62C, 0, 0}},
#endif
#ifdef MMC1_SDR104_MANUAL1
     {0x1758, 0x60100, {0x0, 0, 0}, {0x628, 0, 0}, {0x62C, 0, 0}},
#endif
#ifdef MMC1_VIRTUAL1
     {0x1758, 0x601B0, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef MMC1_VIRTUAL2
     {0x1758, 0x601A0, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef MMC1_VIRTUAL5
     {0x1758, 0x60170, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef MMC1_VIRTUAL6
     {0x1758, 0x60160, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef MMC1_VIRTUAL7
     {0x1758, 0x60150, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif

/* MMC1 - mmc1_dat0 on AA6 - MMC1_MICRO */
#ifdef MMC1_DEFAULT
     {0x175C, 0x60000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef MMC1_DDR_MANUAL1
     {0x175C, 0x60100, {0x630, 751, 0}, {0x634, 0, 0}, {0x638, 20, 0}},
#endif
#ifdef MMC1_SDR104_MANUAL1
     {0x175C, 0x60100, {0x0, 0, 0}, {0x634, 0, 0}, {0x638, 30, 0}},
#endif
#ifdef MMC1_VIRTUAL1
     {0x175C, 0x601B0, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef MMC1_VIRTUAL2
     {0x175C, 0x601A0, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef MMC1_VIRTUAL5
     {0x175C, 0x60170, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef MMC1_VIRTUAL6
     {0x175C, 0x60160, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef MMC1_VIRTUAL7
     {0x175C, 0x60150, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif

/* MMC1 - mmc1_dat1 on Y4 - MMC1_MICRO */
#ifdef MMC1_DEFAULT
     {0x1760, 0x60000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef MMC1_DDR_MANUAL1
     {0x1760, 0x60100, {0x63C, 256, 0}, {0x640, 0, 0}, {0x644, 0, 0}},
#endif
#ifdef MMC1_SDR104_MANUAL1
     {0x1760, 0x60100, {0x0, 0, 0}, {0x640, 0, 0}, {0x644, 0, 0}},
#endif
#ifdef MMC1_VIRTUAL1
     {0x1760, 0x601B0, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef MMC1_VIRTUAL2
     {0x1760, 0x601A0, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef MMC1_VIRTUAL5
     {0x1760, 0x60170, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef MMC1_VIRTUAL6
     {0x1760, 0x60160, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef MMC1_VIRTUAL7
     {0x1760, 0x60150, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif

/* MMC1 - mmc1_dat2 on AA5 - MMC1_MICRO */
#ifdef MMC1_DEFAULT
     {0x1764, 0x60000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef MMC1_DDR_MANUAL1
     {0x1764, 0x60100, {0x648, 263, 0}, {0x64C, 0, 0}, {0x650, 0, 0}},
#endif
#ifdef MMC1_SDR104_MANUAL1
     {0x1764, 0x60100, {0x0, 0, 0}, {0x64C, 0, 0}, {0x650, 0, 0}},
#endif
#ifdef MMC1_VIRTUAL1
     {0x1764, 0x601B0, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef MMC1_VIRTUAL2
     {0x1764, 0x601A0, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef MMC1_VIRTUAL5
     {0x1764, 0x60170, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef MMC1_VIRTUAL6
     {0x1764, 0x60160, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef MMC1_VIRTUAL7
     {0x1764, 0x60150, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif

/* MMC1 - mmc1_dat3 on Y3 - MMC1_MICRO */
#ifdef MMC1_DEFAULT
     {0x1768, 0x60000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef MMC1_DDR_MANUAL1
     {0x1768, 0x60100, {0x654, 0, 0}, {0x658, 0, 0}, {0x65C, 0, 0}},
#endif
#ifdef MMC1_SDR104_MANUAL1
     {0x1768, 0x60100, {0x0, 0, 0}, {0x658, 0, 0}, {0x65C, 0, 0}},
#endif
#ifdef MMC1_VIRTUAL1
     {0x1768, 0x601B0, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef MMC1_VIRTUAL2
     {0x1768, 0x601A0, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef MMC1_VIRTUAL5
     {0x1768, 0x60170, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef MMC1_VIRTUAL6
     {0x1768, 0x60160, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef MMC1_VIRTUAL7
     {0x1768, 0x60150, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif

/* MMC1 - mmc1_sdcd on W7 - MMC1_MICRO */
     {0x176C, 0xE0000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* MMC1 - mmc1_sdwp on Y9 - MMC1_MICRO */
     {0x1770, 0xD0000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* MMC2 - mmc2_clk on J7 - MMC2_EMMC */
#ifdef MMC2_DEFAULT
     {0x149C, 0x60001, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef MMC2_DDR_LB_MANUAL1
     {0x149C, 0x60101, {0x1C8, 592, 2815}, {0x0, 0, 0}, {0x1D0, 422, 0}},
#endif
#ifdef MMC2_STD_HS_LB_MANUAL1
     {0x149C, 0x60101, {0x1C8, 0, 2764}, {0x0, 0, 0}, {0x1D0, 0, 0}},
#endif
#ifdef MMC2_HS200_MANUAL1
     {0x149C, 0x60101, {0x0, 0, 0}, {0x0, 0, 0}, {0x1D0, 935, 280}},
#endif

/* MMC2 - mmc2_cmd on H6 - MMC2_EMMC */
#ifdef MMC2_DEFAULT
     {0x14B0, 0x60001, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef MMC2_DDR_LB_MANUAL1
     {0x14B0, 0x60101, {0x360, 0, 0}, {0x364, 0, 0}, {0x368, 0, 0}},
#endif
#ifdef MMC2_STD_HS_LB_MANUAL1
     {0x14B0, 0x60101, {0x360, 250, 0}, {0x364, 0, 0}, {0x368, 0, 0}},
#endif
#ifdef MMC2_HS200_MANUAL1
     {0x14B0, 0x60101, {0x0, 0, 0}, {0x364, 684, 0}, {0x368, 76, 0}},
#endif

/* MMC2 - mmc2_dat0 on J4 - MMC2_EMMC */
#ifdef MMC2_DEFAULT
     {0x14A0, 0x60001, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef MMC2_DDR_LB_MANUAL1
     {0x14A0, 0x60101, {0x1D4, 384, 0}, {0x1D8, 0, 0}, {0x1DC, 0, 0}},
#endif
#ifdef MMC2_STD_HS_LB_MANUAL1
     {0x14A0, 0x60101, {0x1D4, 1185, 0}, {0x1D8, 0, 0}, {0x1DC, 0, 0}},
#endif
#ifdef MMC2_HS200_MANUAL1
     {0x14A0, 0x60101, {0x0, 0, 0}, {0x1D8, 621, 0}, {0x1DC, 0, 0}},
#endif

/* MMC2 - mmc2_dat1 on J6 - MMC2_EMMC */
#ifdef MMC2_DEFAULT
     {0x14A4, 0x60001, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef MMC2_DDR_LB_MANUAL1
     {0x14A4, 0x60101, {0x1E0, 0, 0}, {0x1E4, 0, 0}, {0x1E8, 0, 0}},
#endif
#ifdef MMC2_STD_HS_LB_MANUAL1
     {0x14A4, 0x60101, {0x1E0, 670, 0}, {0x1E4, 0, 0}, {0x1E8, 0, 0}},
#endif
#ifdef MMC2_HS200_MANUAL1
     {0x14A4, 0x60101, {0x0, 0, 0}, {0x1E4, 183, 0}, {0x1E8, 0, 0}},
#endif

/* MMC2 - mmc2_dat2 on H4 - MMC2_EMMC */
#ifdef MMC2_DEFAULT
     {0x14A8, 0x60001, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef MMC2_DDR_LB_MANUAL1
     {0x14A8, 0x60101, {0x1EC, 171, 0}, {0x1F0, 0, 0}, {0x1F4, 0, 0}},
#endif
#ifdef MMC2_STD_HS_LB_MANUAL1
     {0x14A8, 0x60101, {0x1EC, 972, 0}, {0x1F0, 0, 0}, {0x1F4, 0, 0}},
#endif
#ifdef MMC2_HS200_MANUAL1
     {0x14A8, 0x60101, {0x0, 0, 0}, {0x1F0, 467, 0}, {0x1F4, 0, 0}},
#endif

/* MMC2 - mmc2_dat3 on H5 - MMC2_EMMC */
#ifdef MMC2_DEFAULT
     {0x14AC, 0x60001, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef MMC2_DDR_LB_MANUAL1
     {0x14AC, 0x60101, {0x1F8, 315, 0}, {0x1FC, 0, 0}, {0x200, 54, 0}},
#endif
#ifdef MMC2_STD_HS_LB_MANUAL1
     {0x14AC, 0x60101, {0x1F8, 1116, 0}, {0x1FC, 0, 0}, {0x200, 0, 0}},
#endif
#ifdef MMC2_HS200_MANUAL1
     {0x14AC, 0x60101, {0x0, 0, 0}, {0x1FC, 262, 0}, {0x200, 46, 0}},
#endif

/* MMC2 - mmc2_dat4 on K7 - MMC2_EMMC */
#ifdef MMC2_DEFAULT
     {0x148C, 0x60001, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef MMC2_DDR_LB_MANUAL1
     {0x148C, 0x60101, {0x18C, 49, 0}, {0x190, 0, 0}, {0x194, 170, 0}},
#endif
#ifdef MMC2_STD_HS_LB_MANUAL1
     {0x148C, 0x60101, {0x18C, 850, 0}, {0x190, 0, 0}, {0x194, 0, 0}},
#endif
#ifdef MMC2_HS200_MANUAL1
     {0x148C, 0x60101, {0x0, 0, 0}, {0x190, 274, 0}, {0x194, 162, 0}},
#endif

/* MMC2 - mmc2_dat5 on M7 - MMC2_EMMC */
#ifdef MMC2_DEFAULT
     {0x1490, 0x60001, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef MMC2_DDR_LB_MANUAL1
     {0x1490, 0x60101, {0x1A4, 463, 0}, {0x1A8, 0, 0}, {0x1AC, 81, 0}},
#endif
#ifdef MMC2_STD_HS_LB_MANUAL1
     {0x1490, 0x60101, {0x1A4, 1264, 0}, {0x1A8, 0, 0}, {0x1AC, 0, 0}},
#endif
#ifdef MMC2_HS200_MANUAL1
     {0x1490, 0x60101, {0x0, 0, 0}, {0x1A8, 401, 0}, {0x1AC, 73, 0}},
#endif

/* MMC2 - mmc2_dat6 on J5 - MMC2_EMMC */
#ifdef MMC2_DEFAULT
     {0x1494, 0x60001, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef MMC2_DDR_LB_MANUAL1
     {0x1494, 0x60101, {0x1B0, 8, 0}, {0x1B4, 0, 0}, {0x1B8, 123, 0}},
#endif
#ifdef MMC2_STD_HS_LB_MANUAL1
     {0x1494, 0x60101, {0x1B0, 786, 0}, {0x1B4, 0, 0}, {0x1B8, 0, 0}},
#endif
#ifdef MMC2_HS200_MANUAL1
     {0x1494, 0x60101, {0x0, 0, 0}, {0x1B4, 465, 0}, {0x1B8, 115, 0}},
#endif

/* MMC2 - mmc2_dat7 on K6 - MMC2_EMMC */
#ifdef MMC2_DEFAULT
     {0x1498, 0x60001, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef MMC2_DDR_LB_MANUAL1
     {0x1498, 0x60101, {0x1BC, 0, 102}, {0x1C0, 0, 0}, {0x1C4, 55, 0}},
#endif
#ifdef MMC2_STD_HS_LB_MANUAL1
     {0x1498, 0x60101, {0x1BC, 902, 0}, {0x1C0, 0, 0}, {0x1C4, 0, 0}},
#endif
#ifdef MMC2_HS200_MANUAL1
     {0x1498, 0x60101, {0x0, 0, 0}, {0x1C0, 633, 0}, {0x1C4, 47, 0}},
#endif

/* MMC4 - mmc4_clk on E25 - MMC4_WIFI */
#ifdef MMC4_MANUAL1
     {0x17E8, 0x60103, {0x840, 0, 0}, {0x0, 0, 0}, {0x848, 1147, 0}},
#endif
#ifdef MMC4_DS_MANUAL1
     {0x17E8, 0x60103, {0x840, 0, 0}, {0x0, 0, 0}, {0x848, 0, 0}},
#endif

/* MMC4 - mmc4_cmd on C27 - MMC4_WIFI */
#ifdef MMC4_MANUAL1
     {0x17EC, 0x60103, {0x84C, 1834, 0}, {0x850, 0, 0}, {0x854, 0, 0}},
#endif
#ifdef MMC4_DS_MANUAL1
     {0x17EC, 0x60103, {0x84C, 307, 0}, {0x850, 0, 0}, {0x854, 0, 0}},
#endif

/* MMC4 - mmc4_dat0 on D28 - MMC4_WIFI */
#ifdef MMC4_MANUAL1
     {0x17F0, 0x60103, {0x888, 1935, 128}, {0x88C, 0, 0}, {0x890, 0, 0}},
#endif
#ifdef MMC4_DS_MANUAL1
     {0x17F0, 0x60103, {0x888, 683, 0}, {0x88C, 0, 0}, {0x890, 0, 0}},
#endif

/* MMC4 - mmc4_dat1 on D26 - MMC4_WIFI */
#ifdef MMC4_MANUAL1
     {0x17F4, 0x60103, {0x894, 2172, 44}, {0x898, 0, 0}, {0x89C, 0, 0}},
#endif
#ifdef MMC4_DS_MANUAL1
     {0x17F4, 0x60103, {0x894, 835, 0}, {0x898, 0, 0}, {0x89C, 0, 0}},
#endif

/* MMC4 - mmc4_dat2 on D27 - MMC4_WIFI */
#ifdef MMC4_MANUAL1
     {0x17F8, 0x60103, {0x870, 2165, 0}, {0x874, 0, 0}, {0x878, 0, 0}},
#endif
#ifdef MMC4_DS_MANUAL1
     {0x17F8, 0x60103, {0x870, 785, 0}, {0x874, 0, 0}, {0x878, 0, 0}},
#endif

/* MMC4 - mmc4_dat3 on C28 - MMC4_WIFI */
#ifdef MMC4_MANUAL1
     {0x17FC, 0x60103, {0x87C, 1929, 64}, {0x880, 0, 0}, {0x884, 0, 0}},
#endif
#ifdef MMC4_DS_MANUAL1
     {0x17FC, 0x60103, {0x87C, 613, 0}, {0x880, 0, 0}, {0x884, 0, 0}},
#endif

/* PRCM - rstoutn on F23 - MyPRCM1 */
     {0x1864, 0x20000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PRCM - resetn on E23 - MyPRCM1 */
     {0x185C, 0x60000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* PRUSS1_PRU1 - pr1_pru1_gpi1 on D2 - PR1_PRU1 */
#ifdef PRUSS1_PRU1_DEFAULT
     {0x1578, 0x5000C, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef PR1_PRU1_DIR_IN_MANUAL
     {0x1578, 0x5010C, {0xB1C, 0, 1000}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef PR1_PRU1_PAR_CAP_MANUAL
     {0x1578, 0x5010C, {0xB1C, 2684, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif

/* PRUSS1_PRU1 - pr1_pru1_gpi2 on F4 - PR1_PRU1 */
#ifdef PRUSS1_PRU1_DEFAULT
     {0x157C, 0x5000C, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef PR1_PRU1_DIR_IN_MANUAL
     {0x157C, 0x5010C, {0xB28, 0, 1700}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef PR1_PRU1_PAR_CAP_MANUAL
     {0x157C, 0x5010C, {0xB28, 2904, 234}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif

/* PRUSS1_PRU1 - pr1_pru1_gpi16 on A3 - PR1_PRU1 */
#ifdef PRUSS1_PRU1_DEFAULT
     {0x15B4, 0x5000C, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef PR1_PRU1_DIR_IN_MANUAL
     {0x15B4, 0x5010C, {0xABC, 0, 1100}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef PR1_PRU1_PAR_CAP_MANUAL
     {0x15B4, 0x5010C, {0xABC, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif

/* PRUSS1_PRU1 - pr1_pru1_gpi18 on B4 - PR1_PRU1 */
#ifdef PRUSS1_PRU1_DEFAULT
     {0x15BC, 0x4000C, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef PR1_PRU1_DIR_IN_MANUAL
     {0x15BC, 0x4010C, {0xAE0, 0, 1300}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif

/* PRUSS2_PRU0 - pr2_pru0_gpi1 on E9 - PR2_PRU0 */
#ifdef PRUSS2_PRU0_DEFAULT
     {0x15EC, 0x4000C, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef PR2_PRU0_DIR_IN_MANUAL1
     {0x15EC, 0x4010C, {0xC78, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef PR2_PRU0_PAR_CAP_MANUAL1
     {0x15EC, 0x4010C, {0xC78, 1355, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif

/* PRUSS2_PRU0 - pr2_pru0_gpi2 on F9 - PR2_PRU0 */
#ifdef PRUSS2_PRU0_DEFAULT
     {0x15F0, 0x4000C, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef PR2_PRU0_DIR_IN_MANUAL1
     {0x15F0, 0x4010C, {0xC84, 0, 365}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef PR2_PRU0_PAR_CAP_MANUAL1
     {0x15F0, 0x4010C, {0xC84, 1261, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif

/* PRUSS2_PRU0 - pr2_pru0_gpi3 on F8 - PR2_PRU0 */
#ifdef PRUSS2_PRU0_DEFAULT
     {0x15F4, 0x4000C, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef PR2_PRU0_DIR_IN_MANUAL1
     {0x15F4, 0x4010C, {0xC90, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef PR2_PRU0_PAR_CAP_MANUAL1
     {0x15F4, 0x4010C, {0xC90, 1016, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif

/* PRUSS2_PRU0 - pr2_pru0_gpi4 on E7 - PR2_PRU0 */
#ifdef PRUSS2_PRU0_DEFAULT
     {0x15F8, 0x4000C, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef PR2_PRU0_DIR_IN_MANUAL1
     {0x15F8, 0x4010C, {0xC9C, 0, 218}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef PR2_PRU0_PAR_CAP_MANUAL1
     {0x15F8, 0x4010C, {0xC9C, 1297, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif

/* PRUSS2_PRU0 - pr2_pru0_gpi16 on A8 - PR2_PRU0 */
#ifdef PRUSS2_PRU0_DEFAULT
     {0x1628, 0x5000C, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef PR2_PRU0_DIR_IN_MANUAL1
     {0x1628, 0x5010C, {0xC18, 0, 500}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef PR2_PRU0_PAR_CAP_MANUAL1
     {0x1628, 0x5010C, {0xC18, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif

/* PRUSS2_PRU0 - pr2_pru0_gpi17 on C9 - PR2_PRU0 */
#ifdef PRUSS2_PRU0_DEFAULT
     {0x162C, 0x5000C, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef PR2_PRU0_DIR_IN_MANUAL1
     {0x162C, 0x5010C, {0xC30, 0, 716}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif

/* PRUSS2_PRU0 - pr2_pru0_gpi18 on A9 - PR2_PRU0 */
#ifdef PRUSS2_PRU0_DEFAULT
     {0x1630, 0x5000C, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef PR2_PRU0_DIR_IN_MANUAL1
     {0x1630, 0x5010C, {0xC3C, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif

/* PRUSS2_PRU0 - pr2_pru0_gpi19 on B9 - PR2_PRU0 */
#ifdef PRUSS2_PRU0_DEFAULT
     {0x1634, 0x5000C, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif
#ifdef PR2_PRU0_DIR_IN_MANUAL1
     {0x1634, 0x5010C, {0xC48, 0, 404}, {0x0, 0, 0}, {0x0, 0, 0}},
#endif

/* RTCSS - rtc_porz on AB17 - MyRTCSS1 */
     {0x182C, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* RTCSS - on_off on Y11 - MyRTCSS1 */
     {0x1828, 0x10000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* UART1 - uart1_rxd on B27 - UART1_CONSOLE */
     {0x17E0, 0xC0000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* UART1 - uart1_txd on C26 - UART1_CONSOLE */
     {0x17E4, 0x80000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* UART6 - uart6_rxd on P6 - UART6_BLUETOOTH */
     {0x1450, 0x50008, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* UART6 - uart6_txd on R9 - UART6_BLUETOOTH */
     {0x1454, 0x10008, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* UART6 - uart6_ctsn on R5 - UART6_BLUETOOTH */
     {0x1458, 0x50008, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* UART6 - uart6_rtsn on P5 - UART6_BLUETOOTH */
     {0x145C, 0x10008, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* UART10 - uart10_rxd on E21 - UART10_CAPE */
     {0x1688, 0x50003, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* UART5 - uart5_rxd on B19 - UART5_CAPE */
     {0x172C, 0xD0004, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* UART8 - uart8_rxd on G20 - UART8_CAPE */
     {0x17D0, 0xD0002, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* UART3 - uart3_rxd on A26 - UART3_CAPE */
     {0x17C0, 0x50001, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* USB1 - usb1_dp on AD12 - USB1_TYPEC */
     /* {NOT FOUND, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* USB1 - usb1_dm on AC12 - USB1_TYPEC */
     /* {NOT FOUND, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* USB1 - usb1_drvvbus on AB10 - USB1_TYPEC */
     {0x1680, 0x90000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},

/* USB1 - usb_rxn0 on AF12 - USB1_TYPEC */
     /* {NOT FOUND, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* USB1 - usb_rxp0 on AE12 - USB1_TYPEC */
     /* {NOT FOUND, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* USB1 - usb_txn0 on AC11 - USB1_TYPEC */
     /* {NOT FOUND, 0x10000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* USB1 - usb_txp0 on AD11 - USB1_TYPEC */
     /* {NOT FOUND, 0x10000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* USB2 - usb2_dp on AE11 - USB2_TYPEA */
     /* {NOT FOUND, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* USB2 - usb2_dm on AF11 - USB2_TYPEA */
     /* {NOT FOUND, 0x50000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}}, */

/* USB2 - usb2_drvvbus on AC10 - USB2_TYPEA */
     {0x1684, 0x80000, {0x0, 0, 0}, {0x0, 0, 0}, {0x0, 0, 0}},
};

#ifdef __cplusplus
#if defined(_TMS320C6X) || defined(__TI_ARM_V7M4__)
#pragma CODE_SECTION ("BOARD_IO_DELAY_CODE");
#endif
#endif
uint32_t boardPadGetSize()
{
     return (sizeof(pad) / sizeof(boardPadDelayCfg_t));
}

#ifdef BOARD_PAD_DELAY_ALT_GRP_ENABLE
#ifdef __cplusplus
#if defined(_TMS320C6X) || defined(__TI_ARM_V7M4__)
#pragma CODE_SECTION ("BOARD_IO_DELAY_CODE");
#endif
#endif
uint32_t boardAltPadGetSize()
{
     return (sizeof(altPad) / sizeof(boardPadDelayAltGpCfg_t));
}
#endif
